// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// myDnorm
arma::mat myDnorm(arma::mat X);
RcppExport SEXP survMarkerTwoPhase_myDnorm(SEXP XSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP );
        arma::mat __result = myDnorm(X);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CondSurv_FUN_C
arma::mat CondSurv_FUN_C(arma::mat IPW, arma::colvec xi, arma::uvec di, arma::colvec yi, double tt0, double bw);
RcppExport SEXP survMarkerTwoPhase_CondSurv_FUN_C(SEXP IPWSEXP, SEXP xiSEXP, SEXP diSEXP, SEXP yiSEXP, SEXP tt0SEXP, SEXP bwSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type IPW(IPWSEXP );
        Rcpp::traits::input_parameter< arma::colvec >::type xi(xiSEXP );
        Rcpp::traits::input_parameter< arma::uvec >::type di(diSEXP );
        Rcpp::traits::input_parameter< arma::colvec >::type yi(yiSEXP );
        Rcpp::traits::input_parameter< double >::type tt0(tt0SEXP );
        Rcpp::traits::input_parameter< double >::type bw(bwSEXP );
        arma::mat __result = CondSurv_FUN_C(IPW, xi, di, yi, tt0, bw);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// getWEXP
Rcpp::List getWEXP(arma::mat data, arma::mat Y, int N, arma::mat RT_out, double predictTime, arma::vec resid_sco, double fitvar);
RcppExport SEXP survMarkerTwoPhase_getWEXP(SEXP dataSEXP, SEXP YSEXP, SEXP NSEXP, SEXP RT_outSEXP, SEXP predictTimeSEXP, SEXP resid_scoSEXP, SEXP fitvarSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP );
        Rcpp::traits::input_parameter< int >::type N(NSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type RT_out(RT_outSEXP );
        Rcpp::traits::input_parameter< double >::type predictTime(predictTimeSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type resid_sco(resid_scoSEXP );
        Rcpp::traits::input_parameter< double >::type fitvar(fitvarSEXP );
        Rcpp::List __result = getWEXP(data, Y, N, RT_out, predictTime, resid_sco, fitvar);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
