# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('survMarkerTwoPhase_timesTwo', PACKAGE = 'survMarkerTwoPhase', x)
}

CondSurv_FUN_C <- function(IPW, xi, di, yi, tt0, bw) {
    .Call('survMarkerTwoPhase_CondSurv_FUN_C', PACKAGE = 'survMarkerTwoPhase', IPW, xi, di, yi, tt0, bw)
}

