# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myDnorm <- function(X) {
    .Call('survMarkerTwoPhase_myDnorm', PACKAGE = 'survMarkerTwoPhase', X)
}

CondSurv_FUN_C <- function(IPW, xi, di, yi, tt0, bw) {
    .Call('survMarkerTwoPhase_CondSurv_FUN_C', PACKAGE = 'survMarkerTwoPhase', IPW, xi, di, yi, tt0, bw)
}

getWEXP <- function(data, Y, N, RT_out, predictTime, resid_sco, fitvar) {
    .Call('survMarkerTwoPhase_getWEXP', PACKAGE = 'survMarkerTwoPhase', data, Y, N, RT_out, predictTime, resid_sco, fitvar)
}

getWEXPcutoff <- function(data, subdata, Y, subY, N, RT_out, predictTime, resid_sco, fitvar, cutoffs) {
    .Call('survMarkerTwoPhase_getWEXPcutoff', PACKAGE = 'survMarkerTwoPhase', data, subdata, Y, subY, N, RT_out, predictTime, resid_sco, fitvar, cutoffs)
}

